version: '3'
services:
  backend-dev:
    image: my-backend-dev-image
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - devnetwork

  frontend-dev:
    image: my-frontend-dev-image
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - devnetwork
    depends_on:
      - backend-dev


  backend-prod:
    image: my-backend-prod-image
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - prodnetwork

  frontend-prod:
    image: my-frontend-prod-image
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    networks:
      - prodnetwork
    depends_on:
      - backend-prod

networks:
  devnetwork:
  prodnetwork: